name = "progcareer-contact"
main = "index.js"
compatibility_date = "2024-01-01"

[vars]
CONTACT_TO_EMAIL = "djkatman@gmail.com"

# カスタムドメインはCloudflareダッシュボード > Workers & Pages > progcareer-contact > Settings > Triggers > Custom Domains で設定
# contact.progcareer.com
